#!/usr/bin/env node
fs = require('fs')
var script = process.argv[2];
if (typeof script == 'undefined') {
    console.log("Merci de donner un fichier .malg en argument.");
    process.exit(1);
}
function rec_read(filelist, e) {
    if (filelist.length > 0) {
        var filename = filelist.shift();
        fs.readFile(filename, 'utf8', function (err, content) {
            if (err) {
                return console.log(err);
            }
            if (filename.slice(-3) == '.js') {
                eval(content);
                rec_read(filelist, EMULISP_CORE);
            } else {
                e.eval(content);
                rec_read(filelist, e);
            }
        });
    }
}
rec_read(['emulisp/emulisp_core.js',
          'microalg.l', process.argv[2]]);
